images:
  brick: https://raw.githubusercontent.com/redbrick/design-system/main/assets/logos/redbrick.svg
  emote: https://raw.githubusercontent.com/redbrick/design-system/main/assets/logos/resign-emote.png
  logo: https://raw.githubusercontent.com/redbrick/design-system/main/assets/logos/logo.png
society:
  name: LU Cyber Defense Club
  tagline: Lewis University's cyber competition team.
navigation:
  global:
    - text: Blog
      link: /blog
    - text: Competitions
      link: /competitions
    - text: Pilots Handbook
      link: https://ph.dj.je/
  blog:
    - text: Events
      tag: events
    - text: Admin Blog
      tag: admins
    - text: Tutorials
      tag: tutorial
    - text: Conferences
      tag: conferences
    - text: Newsletters
      tag: newsletter
  buttons:
    primary:
      text: Signup
      link: https://join.redbrick.dcu.ie
    secondary:
      text: Discord
      link: https://discord.redbrick.dcu.ie
drawer: navigation
home:
  hero:
    title:
      secondary: Lewis University Cyber Defense Club.
      primary: National Championship Winning Team.
    body: The CaMS Cyber Defense Club offers students hands-on opportunities to become cyber security experts. We work together to learn the concepts, skills, and tools modern cyber security warriors need to defend mission-critical systems. One of the things that makes this activity unique is that it is entirely student-run. That way, it really serves as the perfect complement to all the security-focused coursework you can take as a Computer Science student at Lewis University.
    buttons:
      primary:
        text: Signup
        link: https://join.redbrick.dcu.ie
      secondary:
        text: Discord
        link: https://discord.redbrick.dcu.ie
  cta:
    title: Don't Miss Out
    body: Lewis University is a nationally recognized Center of Academic Excellence in Information Assurance Education by the Department of Homeland Security & the National Security Agency
    button:
      text: Join us today
      link: https://join.redbrick.dcu.ie
    gallery:
      r1c1: https://cdn.redbrick.dcu.ie/atlas/static/img/tagging-24.jpg
      r1c2: https://cdn.redbrick.dcu.ie/atlas/static/img/newsletter-snap.webp
      r1c3: https://cdn.redbrick.dcu.ie/atlas/static/img/hacker.jpg
      r2c1: https://cdn.redbrick.dcu.ie/atlas/static/img/browner-explains.jpg
      r2c2: https://cdn.redbrick.dcu.ie/atlas/static/img/sistem-mag1c.jpg
      r2c3: https://cdn.redbrick.dcu.ie/atlas/static/img/working.jpg
      r3c1: https://cdn.redbrick.dcu.ie/atlas/static/img/hecker.jpg
      r3c2: https://cdn.redbrick.dcu.ie/atlas/static/img/cmt-24-25.jpg
      r3c3: https://cdn.redbrick.dcu.ie/atlas/static/img/CSBallCmt24.jpg
  committee:
    - name: David Simeone
      position: 🛡️ Co-admin
      username: djsime1
      image: https://github.com/djsime1.png
    - name: Nicolas Formella
      position: 🛡️ Co-admin
      username: GlitchGecko
      image: https://github.com/Glitch-Gecko.png
    - name: Kacper Z
      position: 🤵‍♂️ Administrative assistant
      username: girimuszek
      image: https://github.com/Glitch-Gecko.png
    - name: Michael S
      position: 🤵‍♂️ Administrative assistant
      username: wikey
      image: https://github.com/Glitch-Gecko.png
    - name: Alex Florczyk
      position: 📜 Cyber-policy guru
      username: awesomealey
      image: https://github.com/Glitch-Gecko.png
    - name: Dr. Jason Perry
      position: 👨‍🏫 Faculty supervisor
      username: jasonp_cybsec
      image: https://github.com/Glitch-Gecko.png
    - name: Huda Hajira
      position: 📱 Social media manager
      username: huda-code
      image: https://github.com/huda-code.png
