images:
  icon: /assets/svg/flamingo.svg
  emote: https://cdn.discordapp.com/emojis/894695092231757885.webp
  logo: /assets/svg/flamingo.svg
society:
  name: LU Cyber Defense Club
  tagline: Lewis University's cyber competition team.
navigation:
  global:
    - text: Blog
      link: /blog
    - text: Pilots Handbook
      link: https://wiki.lewiscyber.club/
  blog:
    - text: Events
      tag: events
    - text: Admin Blog
      tag: admins
    - text: Tutorials
      tag: tutorial
    - text: Conferences
      tag: conferences
    - text: Newsletters
      tag: newsletter
  buttons:
    primary:
      text: Register
      link: /register
    secondary:
      text: Member portal
      link: https://portal.lewiscyber.club
drawer: navigation
home:
  hero:
    title:
      secondary: Lewis University Cyber Defense Club.
      primary: National Championship Winning Team.
    body: The CaMS Cyber Defense Club offers students hands-on opportunities to become cyber security experts. We work together to learn the concepts, skills, and tools modern cyber security warriors need to defend mission-critical systems. One of the things that makes this activity unique is that it is entirely student-run. That way, it really serves as the perfect complement to all the security-focused coursework you can take as a Computer Science student at Lewis University.
    buttons:
      primary:
        text: Start here
        link: /register
      secondary:
        text: Discord guild
        link: /discord
  cta:
    title: Don't Miss Out
    body: Lewis University is a nationally recognized Center of Academic Excellence in Information Assurance Education by the Department of Homeland Security & the National Security Agency
    button:
      text: Join us today
      link: /register
    gallery:
      r1c1: https://cdn.lewiscyber.club/gallery/grid01.webp
      r1c2: https://cdn.lewiscyber.club/gallery/grid02.webp
      r1c3: https://cdn.lewiscyber.club/gallery/grid03.webp
      r2c1: https://cdn.lewiscyber.club/gallery/grid04.webp
      r2c2: https://cdn.lewiscyber.club/gallery/grid05.webp
      r2c3: https://cdn.lewiscyber.club/gallery/grid06.webp
      r3c1: https://cdn.lewiscyber.club/gallery/grid07.webp
      r3c2: https://cdn.lewiscyber.club/gallery/grid08.webp
      r3c3: https://cdn.lewiscyber.club/gallery/grid09.webp
  committee:
    - name: David Simeone
      position: 👨‍🎓 Emeritus President
      username: djsime1
      image: https://cdn.lewiscyber.club/portraits/David.webp
    - name: Dr. Jason Perry
      position: 👨‍🏫 Faculty supervisor
      username: jasonp_cybsec
      image: https://cdn.lewiscyber.club/portraits/Perry.webp
  schedule:
    semester: Spring 2026
    day: Monday
    time: 2:30-4:00 PM
    location: AS-101-S
